name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Make production
        run: sh build.sh
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: make build branch
          branch: build
          push_options: "--force"
