name: Deploy relact to server

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: Production
        run: sh prod.sh
      - name: Reset
        run: git reset --hard
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://103.214.112.18
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
